language: python


dist: xenial
services:
  - xvfb


env:
  - PYTHON=3.6 DEPS=pinned MPLBACKEND=agg DOCTESTS=false
  - PYTHON=3.6 DEPS=latest MPLBACKEND=agg DOCTESTS=true
  - PYTHON=3.7 DEPS=latest MPLBACKEND=agg DOCTESTS=true
  - PYTHON=3.8 DEPS=latest MPLBACKEND=agg DOCTESTS=true
  - PYTHON=3.8 DEPS=latest MPLBACKEND=qt5agg DOCTESTS=true
  - PYTHON=3.8 DEPS=minimal MPLBACKEND=agg DOCTESTS=false


before_install:
  - sudo apt-get update -yq
  - sudo sh ci/getmsfonts.sh
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no 
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda config --set channel_priority false
  - conda info -a


install:
  - conda create -n testenv pip python=$PYTHON
  - source activate testenv
  - cat ci/deps_${DEPS}.txt ci/utils.txt > deps.txt
  - conda install --file deps.txt
  - pip install .


before_script:
  - if [ $MPLBACKEND == "qtagg" ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi


script:
  - make lint
  - if [ $DOCTESTS == 'true' ];
    then make coverage;
    else make unittests;
    fi


after_success:
    - pip install codecov
    - codecov
